export interface AuthUser {
  id: number;
  name: string;
  relativeName?: string;
  epicId?: string;
  email?: string;
  phone?: string | null;
  role: 'admin' | 'voter' | 'aspirant';
  age?: number;
  address?: string;
  aspirantId?: number;
  aspirantWardNumber?: string;
  wardId?: number;
  wardNumber?: string;
  wardName?: string;
  ward?: {
    id?: number;
    number?: string;
    name?: string;
    state?: string;
    parliamentary?: string;
    assembly?: string;
    zone?: string;
    createdAt?: string;
    updatedAt?: string;
  };
  constituency?: string;
  state?: string;
  parliamentary?: string;
  assembly?: string;
  corporationName?: string;
  corporationNameL1?: string;
  psName?: string;
  psNameL1?: string;
  psLong?: string;
  psLat?: string;
  voterEpic?: string;
  gender?: string;
  profilePicture?: string | null;
  isChat?: boolean;
  isMeeting?: boolean;
  isDirectMeet?: boolean;
  isPhoneCall?: boolean;
  hasVoted?: boolean;
  electionId?: number;
  electionType?: string;
  electionName?: string;
  constituencyId?: number;
  constituencyName?: string;
}
